export const products = [
  {
    id: 21,
    productName: 'Marble Queen pothos',
    currentPrice: 18.99,
    previousPrice: 31.99,
    height: '30-40 cm',
    imgUrl: './products/img/139485.jpg',
    itemNo: 139485,
    category: 'Hanging',
    botanicName: "Epipremnum pinnatum 'Marble Queen'",
    description: 'Pothos are a family of beautiful vines that are popularly known as devil’s ivy. This is for two reasons, neither of them sinister. First, in the wild they thrive in dark places. Second, they’re almost impossible to kill. They’ll take a lot of neglect. Not that we’re suggesting you neglect them. While it will easily tolerate dry, shady conditions, it will be happiest if you water it whenever the top two inches of soil feel dry, put it somewhere bright, but out of direct sun, and give it a feed with liquid fertiliser once a month in spring and summer.',
    light: 'Most light conditions. She’ll be happy in anything from shade to bright light (but not direct sun). Her color may darken in low light.',
    watering: 'Light watering. She’s drought tolerant, so good for forgetful waterers, but try to water her when the top two inches of soil feel dry.',
    humidity: 'Humidity. She loves a moist environment, so will be very happy in a bathroom or with regular misting.',
    petBabySafe: 'No. Toxic if ingested',
    easyCare: 'Yes. Almost unkillable',
    inStock: 8,
  },
  {
    id: 22,
    productName: 'Peace Lily white sails',
    currentPrice: 10.99,
    previousPrice: 25.99,
    height: '40-100 cm',
    imgUrl: './products/img/496631.jpg',
    itemNo: 496631,
    category: 'Flowering',
    botanicName: 'Spathiphyllum wallisii',
    description: "As you may have guessed from its love of steamy conditions, the peace lily is native to tropical rainforests, specifically those of South and Central America. As exotic as it looks, its light and water needs are modest. It will cope in quite low light, though prefers indirect light, and as long as its humidity needs are met it's generally happy and should flower throughout spring. It will appreciate a feed with liquid fertiliser once per month in spring and summer. As well as being an elegant beauty, this plant is a hardworking air-purifyer.",
    light: 'Most light conditions. She’s easy when it comes to light, managing in most conditions, though she’ll flower more in a brighter spot.',
    watering: 'Light watering. She’s pretty tough and will usually bounce back from a missed watering. Water her when the top inch of soil feels dry.',
    humidity: 'Humidity. She loves humidity. If your bathroom gets lots of light, pop her in there. Or mist her every few days to keep her happy.',
    petBabySafe: 'No. Toxic to cats and dogs',
    easyCare: 'Yes.',
    inStock: 6,
  },
  {
    id: 23,
    productName: 'String of nickels',
    currentPrice: 19.99,
    previousPrice: 28.99,
    height: '35-45 cm',
    imgUrl: './products/img/849454.jpg',
    itemNo: 849454,
    category: 'Hanging',
    botanicName: 'Dischidia imbricata',
    description: 'In the wild, it gets most of its required water and nutrients from the air. Remembering that is a good way to understand how to care for it. Don’t water it too frequently, but mist it regularly. Basically, do your best impression of a tropical rainforest. As it’s used to living in the shade of the forest, it doesn’t need much light. Remember to also give it a feed with liquid fertiliser once per month in spring and summer.',
    light: 'Medium light. He can tolerate partial shade, perfect for those rooms with medium light.',
    watering: 'Light watering. He needs very little water, so let his soil totally dry out between drinks. Let all excess water drain off.',
    humidity: 'He loves moist air. He’ll enjoy living in a steamy bathroom, or give him a good mist a couple of times a week.',
    petBabySafe: 'No. Mildly toxic if ingested',
    easyCare: 'Yes.',
    inStock: 4,
  },
  {
    id: 24,
    productName: 'Boston Fern',
    currentPrice: 17.99,
    previousPrice: 22.99,
    height: '5-50 cm',
    imgUrl: './products/img/245781.jpg',
    itemNo: 245781,
    category: 'Ferns',
    botanicName: 'Nephrolepis Exaltata',
    description: "You’ll find Boston Ferns in the wild in humid, shady areas, like swamps and forests, in South and Central America, the West Indies and Africa. They love anywhere wet, hot and not too bright. When looking after one at home, the rule is to never let a Boston fern dry out. Make sure to keep the soil moist and humidity level high. Although it's very tempting, try to resist touching their fronds as they really don't like it and it might turn them brown. To encourage lots of healthy growth, give it a feed with liquid fertiliser once per month in spring and summer.",
    light: 'Most light conditions. Like a lot of ferns, she’s used to living in partial shade, so she’s ideal for a room with lower light.',
    watering: 'Frequent watering. She likes moist soil, so check her weekly and water whenever the top inch of soil is dry. Let any excess drain off.',
    humidity: 'She really really loves humidity. Mist her a couple of times a week or let her live in the bathroom, basking happily in steam.',
    petBabySafe: 'Yes.',
    easyCare: 'Somewhat.',
    inStock: 4,
  },
  {
    id: 25,
    productName: 'Pineapple plant',
    currentPrice: 25.00,
    previousPrice: 25.00,
    height: '40-50 cm',
    imgUrl: './products/img/658972.jpg',
    itemNo: 658972,
    category: 'Flowering',
    botanicName: 'Ananas Champaca',
    description: 'Originally grown in the southern states of America and South America. This pineapple grows on top of the plant’s sword-like leaves, first appearing as tubular purple flowers in summer before turning into small fruits. As spectacular as they look, you wouldn’t want to eat these pineapples, as the fruit can sometimes be toxic. Despite their showy appearance, pineapple plants are easy to look after. They’re not fussed about humidity and don’t need pruning, they just like a decent amount of sunlight and regular watering. This is especially true when they’re flowering or producing fruit - that’s thirsty work.',
    light: 'Bright light. They like plenty of bright light to give them the energy they need to grow their impressive flowers and fruit.',
    watering: 'Regular watering. They enjoy regular watering, especially if they’re in a sunny spot. Check the soil before you next water, it should dry out between waterings to avoid root rot.',
    humidity: 'Room level of humidity, apart from winter when Pineapple Plant can use more',
    petBabySafe: 'Yes. Non-toxic',
    easyCare: 'Yes.',
    inStock: 3,
  },
];
