export const GET_PRODUCTS = 'GET_PRODUCTS';
export const TOGGLE_PRODUCT_IN_CART = 'TOGGLE_PRODUCT_IN_CART';
export const INCREMENT_QUANTITY_PRODUCT_IN_CART = 'INCREMENT_QUANTITY_PRODUCT_IN_CART';
export const DECREMENT_QUANTITY_PRODUCT_IN_CART = 'DECREMENT_QUANTITY_PRODUCT_IN_CART';
export const DELETE_CART = 'DELETE_CART';
