export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const PAGINATION_NUMBER = 'PAGINATION_NUMBER';
export const SET_CURREN_PAGE = 'SET_CURREN_PAGE';
export const NEXT_PAGE_CATALOG = 'NEXT_PAGE_CATALOG';
export const PREVIOUS_PAGE_CATALOGE = 'PREVIOUS_PAGE_CATALOGE';
